name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Setting up dotnet 8 as default SDK
        run: |
          dotnet new globaljson --sdk-version 8.0.0 --roll-forward minor
          dotnet --version
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test
      - name: Pack nugets
        run: dotnet pack -c Release -o bin
      - name: Publish nugets
        env:
            NUGET_FEED: https://api.nuget.org/v3/index.json
            NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push --skip-duplicate -s $NUGET_FEED -k $NUGET_KEY bin/**/*.nupkg
        